version: "3"

services:

  react:
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - fullstack
    depends_on:
      - go
    tty: true

  go:
    ports:
      - 8080:8080
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - fullstack
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql
    command: --init-file /app/db-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Scout-DB
    container_name: db
    ports:
      - 6000:6000
    volumes:
      - database_mysql:/var/lib/mysql
      - ./backend/db-init.sql:/app/db-init.sql
    networks:
      - fullstack

volumes:
  database_mysql:

networks:
  fullstack:
    driver: bridge
